export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_START = 'GET_ARTICLES_START';
export const GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR';
export const GET_ARTICLE = 'GET_ARTICLE';
export const MY_ARTICLES = 'MY_ARTICLES';
export const NEW_ARTICLE = 'NEW_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const LOAD_PROGRESS = 'LOAD_PROGRESS';
export const SUBMISSION_FAILED = 'SUBMISSION_FAILED';

// signup actions
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const IS_SIGNING_UP = 'IS_SIGNING_UP';
