export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_START = 'GET_ARTICLES_START';
export const GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR';
export const GET_AVERAGE_RATE_SUCCESS = 'GET_AVERAGE_RATE_SUCCESS';
export const GET_AVERAGE_RATE_ERROR = 'GET_AVERAGE_RATE_ERROR';
export const RATE_ARTICLE_SUCCESS = 'RATE_ARTICLE_SUCCESS';
export const RATE_ARTICLE_ERROR = 'RATE_ARTICLE_ERROR';
