export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_START = 'GET_ARTICLES_START';
export const GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR';
export const RATE_AVERAGE_SUCCESS = 'RATE_AVERAGE_SUCCESS';
export const RATE_AVERAGE_ERROR = 'RATE_AVERAGE_ERROR';
export const RATE_ARTICLE_SUCCESS = 'RATE_ARTICLE_SUCCESS';
export const RATE_ARTICLE_ERROR = 'RATE_ARTICLE_ERROR';
